### ISSUE TITLE
让我们来新建readme吧！

### ISSUE THREAD

**Issue by misaka-clover** [Misaka-9936/SCUT-Software-Team-Building-2020#7]
大家有空的话也一起来修改一下readme吧，那毕竟是我们repository的门面嘛，比如添加一点自我介绍什么的啦！

有什么疑问的话可以在这个Issue下留言喔！

**Comment by misaka-clover** [comment]
> 大家有空的话也一起来修改一下readme吧，那毕竟是我们repository的门面嘛，比如添加一点自我介绍什么的啦！
> 
> 有什么疑问的话可以在这个Issue下留言喔！

（我先做一个示范吧要不

**Comment by fujihan** [comment]
收到

**Comment by misaka-clover** [comment]
对了，任何的修改（包括readme）最好都要新建一个分支喔，别在master上改啦。

而且分支名也一定要改哦，默认的名字很容易让人困惑。

**Comment by fujihan** [comment]
好的好的，了解了解，没问题没问题

**Comment by Hello-World-67** [comment]
了解了解，好的好的，没问题没问题

**Comment by misaka-clover** [comment]
> 好的好的，了解了解，没问题没问题

？？？谢谢，感觉有被敷衍到

**Comment by fujihan** [comment]
报告，创建不了分支了，请求分享权限

**Comment by misaka-clover** [comment]
> 报告，创建不了分支了，请求分享权限

完了，我也不知道哪里出了问题了，出大问题了兄弟们。

（这不应该啊QAQ
